-- AUTO-GENERATED by fricas_bridge/proof_discharger.py
-- DO NOT EDIT BY HAND — regenerate with:
--   python fricas_bridge/proof_discharger.py --generate
--
-- Four Class A Risch–Bronstein HasDerivAt theorems, auto-discharged.
-- Each proof is produced mechanically from the FriCAS antiderivative shape.
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv
import Mathlib.Tactic

noncomputable section
open Real

theorem autodischarge_001 (x : ℝ) :
    HasDerivAt (fun t : ℝ => Real.log (t ^ 2 + 1) ^ 2 / 2 + t ^ 2 / 2 - Real.log (t ^ 2 + 1) / 2)
               ((2 * x * Real.log (x ^ 2 + 1) + x ^ 3) / (x ^ 2 + 1)) x := by
  have hpos : (0 : ℝ) < x ^ 2 + 1 := by positivity
  have hne  : (x ^ 2 + 1 : ℝ) ≠ 0 := hpos.ne'
  have hg : HasDerivAt (fun t : ℝ => t ^ 2 + 1) (2 * x) x := by
    have h := (hasDerivAt_pow 2 x).add (hasDerivAt_const x (1 : ℝ))
    simpa [pow_one] using h
  have hL : HasDerivAt (fun t : ℝ => Real.log (t ^ 2 + 1)) (2 * x / (x ^ 2 + 1)) x :=
    hg.log hne
  have hL2 : HasDerivAt (fun t : ℝ => Real.log (t ^ 2 + 1) ^ 2 / 2)
      (Real.log (x ^ 2 + 1) * (2 * x / (x ^ 2 + 1))) x := by
    have hsq : HasDerivAt (fun u : ℝ => u ^ 2 / 2) (Real.log (x ^ 2 + 1))
               (Real.log (x ^ 2 + 1)) := by
      have h := (hasDerivAt_pow 2 (Real.log (x ^ 2 + 1))).div_const 2
      convert h using 1
      simp [pow_one]; ring
    exact hsq.comp x hL
  have hx2 : HasDerivAt (fun t : ℝ => t ^ 2 / 2) x x := by
    have h := (hasDerivAt_pow 2 x).div_const 2
    convert h using 1
    simp [pow_one]; ring
  have hL1 : HasDerivAt (fun t : ℝ => Real.log (t ^ 2 + 1) / 2) (x / (x ^ 2 + 1)) x := by
    have h := hL.div_const 2
    convert h using 1
    field_simp [hne]
  have hF : HasDerivAt
      (fun t : ℝ => Real.log (t ^ 2 + 1) ^ 2 / 2 + t ^ 2 / 2 - Real.log (t ^ 2 + 1) / 2)
      (Real.log (x ^ 2 + 1) * (2 * x / (x ^ 2 + 1)) + x - x / (x ^ 2 + 1)) x :=
    (hL2.add hx2).sub hL1
  convert hF using 1
  field_simp [hne]
  ring

theorem autodischarge_003 (x : ℝ) :
    HasDerivAt (fun t : ℝ => Real.log (t ^ 2 + 1) / 2)
               (x / (x ^ 2 + 1)) x := by
  have hpos : (0 : ℝ) < x ^ 2 + 1 := by positivity
  have hne : (x ^ 2 + 1 : ℝ) ≠ 0 := hpos.ne'
  have hg : HasDerivAt (fun t : ℝ => t ^ 2 + 1) (2 * x) x := by
    have h := (hasDerivAt_pow 2 x).add (hasDerivAt_const x (1 : ℝ))
    simpa [pow_one] using h
  have h := (hg.log hne).div_const 2
  convert h using 1
  field_simp [hne]

theorem autodischarge_004 (x : ℝ) :
    HasDerivAt (fun t : ℝ => Real.arctan (t ^ 2))
               (2 * x / (1 + x ^ 4)) x := by
  have hg : HasDerivAt (fun t : ℝ => t ^ 2) (2 * x) x := by
    have h := hasDerivAt_pow 2 x
    simpa [pow_one] using h
  have hF := (Real.hasDerivAt_arctan (x ^ 2)).comp x hg
  convert hF using 1
  have h1 : (0 : ℝ) < 1 + x ^ 4        := by positivity
  have h2 : (0 : ℝ) < 1 + (x ^ 2) ^ 2  := by positivity
  field_simp [h1.ne', h2.ne']
  ring

theorem autodischarge_006 (x : ℝ) :
    HasDerivAt (fun t : ℝ => Real.arctan (t + 1))
               (1 / (x ^ 2 + 2 * x + 2)) x := by
  have hg : HasDerivAt (fun t : ℝ => t + 1) 1 x := by
    simpa using (hasDerivAt_id x).add (hasDerivAt_const x (1 : ℝ))
  have hF := (Real.hasDerivAt_arctan (x + 1)).comp x hg
  convert hF using 1
  have h1 : (0 : ℝ) < 1 + (x + 1) ^ 2 := by positivity
  have h2 : (0 : ℝ) < x ^ 2 + 2 * x + 2 := by nlinarith [sq_nonneg (x + 1)]
  field_simp [h1.ne', h2.ne']
  ring
end
