"""
Tier 8.1 — Coq / Coquelicot proof emitter.

Translates a FriCAS antiderivative (same shape-classified representation used
by proof_discharger.py) into a self-contained Coq proof script using the
Coquelicot library for real analysis.

The *cross-prover certificate* (Tier 8.2) is one integral kernel-verified in
both Lean 4 (via RischAutoDischarge.lean) and Coq (via this emitter) with no
shared trusted base — two independent kernels, one mathematical fact.

Supported antiderivative shapes
--------------------------------
COMPLEX_SUM      atan(x)·log(…) compound          no hypotheses
LOG_POS_QUAD     log(x²+c)/2                       no hypotheses
ARCTAN_POW       atan(x^n)                         no hypotheses
ARCTAN_LINEAR    atan(x+c)                         no hypotheses
LOG_SIMPLE       log(x)                            h: x <> 0
LOG_NEG_QUAD     log(x²-c)/2                       h: x²-c <> 0
LOG_PFD (C)      log(x)/2 - log(x+1) …  2 poles   h: x, x+a <> 0
LOG_PFD (D)      log(x)/2 - …           3 poles   h: x, x+1, x+2 <> 0

Public API
----------
CoqProof                        dataclass
emit_coq(claim_id)              → CoqProof
emit_coq_from_antideriv(
    antideriv, integrand,
    hypotheses, theorem_name)   → CoqProof
emit_all()                      → list[CoqProof]
write_coq_file(path)            → Path
"""
from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from fricas_bridge.proof_discharger import (
    classify_antideriv,
    synthesize_hypotheses,
    _spec_for,
    _ALL_CLAIMS,
    FRICAS_CACHE,
)

_HEADER = """\
(* Auto-generated by ProofForge Ω cross_prover/coq_emitter.py
   Library: Coquelicot 3.x  (https://coquelicot.saclay.inria.fr/)
   This file is the Coq half of the cross-prover certificate (Tier 8.2).
   Each theorem is independently kernel-checked by Coq; the matching Lean 4
   theorem lives in fricas_bridge/RischAutoDischarge.lean. *)

Require Import Reals Coquelicot.Coquelicot.
Open Scope R_scope.
"""

_FOOTER = "\n(* end of generated file *)\n"


@dataclass
class CoqProof:
    theorem_name: str           # "coq_autodischarge_001"
    claim_id: str               # "pf.integral.bronstein_001"
    integrand: str              # Lean-style integrand string
    antideriv: str              # Lean-style antideriv body
    hypotheses: list[str]       # ["hx : x <> 0"]   (Coq syntax)
    statement: str              # full Coq theorem statement
    proof_script: str           # tactic proof
    antideriv_shape: str        # classify_antideriv key

    @property
    def full_text(self) -> str:
        return self.statement + "\n" + self.proof_script + "\n"


# ---------------------------------------------------------------------------
# Expression translator: Lean → Coq/Coquelicot
# ---------------------------------------------------------------------------

def _lean_to_coq_expr(expr: str, *, rename_bound: bool = False) -> str:
    """
    Translate a Lean-flavoured expression to Coq/Coquelicot notation.

    rename_bound=True replaces the lambda-bound variable `t` with `x` (used
    when translating antideriv bodies that use `t` as the bound variable).
    """
    e = expr
    e = re.sub(r"Real\.log", "ln", e)
    e = re.sub(r"Real\.arctan", "atan", e)
    e = re.sub(r"Real\.sqrt", "sqrt", e)
    e = e.replace("ℝ", "R")
    e = e.replace("≠", "<>")
    e = e.replace("∧", r"/\\")
    if rename_bound:
        # Replace standalone `t` (bound variable) with `x` — avoid touching
        # substrings like `atan`, `sqrt`.  Use word-boundary matching.
        e = re.sub(r"\bt\b", "x", e)
    return e


def _coq_hypotheses(hyp_objects: list) -> list[str]:
    """Convert proof_discharger Hypothesis objects → Coq hypothesis strings."""
    coq_hyps: list[str] = []
    for h in hyp_objects:
        # h.lean_binder looks like "(hx : x ≠ 0)"
        binder = h.lean_binder.strip("()")
        name, _, stmt = binder.partition(" : ")
        coq_stmt = _lean_to_coq_expr(stmt.strip())
        coq_hyps.append(f"{name.strip()} : {coq_stmt}")
    return coq_hyps


def _forall_params(coq_hyps: list[str]) -> str:
    """Build Coq ∀-style parameter list; always includes (x : R)."""
    parts = ["(x : R)"]
    for h in coq_hyps:
        parts.append(f"({h})")
    return " ".join(parts)


# ---------------------------------------------------------------------------
# Shape-specific proof tactics
# ---------------------------------------------------------------------------

def _proof_class_a() -> str:
    return textwrap.dedent("""\
    Proof.
      auto_derive; try ring.
    Qed.""")


def _proof_class_a_trig() -> str:
    return textwrap.dedent("""\
    Proof.
      auto_derive;
        try (apply Rgt_not_eq; lra);
        field_simplify; ring.
    Qed.""")


def _proof_class_b() -> str:
    """Single non-zero hypothesis (log(x) or log(x^2-c)/2)."""
    return textwrap.dedent("""\
    Proof.
      auto_derive; [exact hx | field_simplify; ring].
    Qed.""")


def _proof_class_c() -> str:
    """Two-pole PFD — two non-zero hypotheses hx, hx1."""
    return textwrap.dedent("""\
    Proof.
      auto_derive;
        [exact hx | exact hx1 | field_simplify [hx hx1]; ring].
    Qed.""")


def _proof_class_d() -> str:
    """Three-pole PFD — hypotheses hx, hx1, hx2."""
    return textwrap.dedent("""\
    Proof.
      auto_derive;
        [exact hx | exact hx1 | exact hx2 |
         field_simplify [hx hx1 hx2]; ring].
    Qed.""")


def _proof_for_shape(shape: str, n_hyps: int) -> str:
    if shape in ("LOG_SIMPLE", "LOG_NEG_QUAD"):
        return _proof_class_b()
    if shape == "LOG_PFD":
        return _proof_class_c() if n_hyps == 2 else _proof_class_d()
    if shape in ("ARCTAN_POW", "ARCTAN_LINEAR", "COMPLEX_SUM"):
        return _proof_class_a_trig()
    return _proof_class_a()


# ---------------------------------------------------------------------------
# Statement builder
# ---------------------------------------------------------------------------

def _build_statement(
    theorem_name: str,
    integrand_coq: str,
    antideriv_coq: str,
    coq_hyps: list[str],
) -> str:
    params = _forall_params(coq_hyps)
    return (
        f"Theorem {theorem_name} {params} :\n"
        f"  is_derive (fun x => {antideriv_coq}) x ({integrand_coq})."
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def emit_coq_from_antideriv(
    antideriv: str,
    integrand: str,
    *,
    theorem_name: str,
    claim_id: str = "unknown",
) -> CoqProof:
    """Emit one Coq proof from raw antiderivative / integrand strings."""
    shape_dict = classify_antideriv(antideriv)
    shape = shape_dict.get("shape", "UNKNOWN")
    hyp_objects = synthesize_hypotheses(antideriv)
    coq_hyps = _coq_hypotheses(hyp_objects)

    antideriv_coq = _lean_to_coq_expr(antideriv)
    integrand_coq = _lean_to_coq_expr(integrand)
    proof_script = _proof_for_shape(shape, len(coq_hyps))
    statement = _build_statement(theorem_name, integrand_coq, antideriv_coq, coq_hyps)

    return CoqProof(
        theorem_name=theorem_name,
        claim_id=claim_id,
        integrand=integrand,
        antideriv=antideriv,
        hypotheses=coq_hyps,
        statement=statement,
        proof_script=proof_script,
        antideriv_shape=shape,
    )


def emit_coq(claim_id: str) -> CoqProof:
    """Emit a Coq proof for a named Bronstein claim."""
    spec = _spec_for(claim_id)
    fricas_antideriv = FRICAS_CACHE[claim_id]["antideriv_fricas"]
    suffix = claim_id.split("_")[-1] if "_" in claim_id else claim_id

    shape_dict = classify_antideriv(fricas_antideriv)
    shape = shape_dict.get("shape", "UNKNOWN")
    hyp_objects = synthesize_hypotheses(fricas_antideriv)
    coq_hyps = _coq_hypotheses(hyp_objects)

    antideriv_coq = _lean_to_coq_expr(spec.antideriv_body, rename_bound=True)
    integrand_coq = _lean_to_coq_expr(spec.integrand_expr)
    proof_script = _proof_for_shape(shape, len(coq_hyps))
    theorem_name = f"coq_autodischarge_{suffix}"
    statement = _build_statement(theorem_name, integrand_coq, antideriv_coq, coq_hyps)

    return CoqProof(
        theorem_name=theorem_name,
        claim_id=claim_id,
        integrand=spec.integrand_expr,
        antideriv=spec.antideriv_body,
        hypotheses=coq_hyps,
        statement=statement,
        proof_script=proof_script,
        antideriv_shape=shape,
    )


def emit_all() -> list[CoqProof]:
    """Emit Coq proofs for all nine Risch–Bronstein claims."""
    return [emit_coq(cid) for cid in _ALL_CLAIMS]


def write_coq_file(path: Optional[str] = None) -> Path:
    """
    Write a self-contained .v file containing all nine Coq theorems.

    Returns the Path of the written file.
    """
    dest = Path(path) if path else Path(__file__).parent / "RischCoqDischarge.v"
    proofs = emit_all()
    parts = [_HEADER]
    for p in proofs:
        parts.append(f"\n(* Claim: {p.claim_id} | shape: {p.antideriv_shape} *)")
        parts.append(p.full_text)
    parts.append(_FOOTER)
    dest.write_text("\n".join(parts))
    return dest
