"""
Tier 8.3 — Isabelle/HOL proof emitter.

Translates the same FriCAS antiderivative representation to Isabelle/HOL
syntax using the Analysis library (DERIV, has_field_derivative).

This is the third prover in the cross-prover stack:
  Lean 4 + Mathlib    → RischAutoDischarge.lean
  Coq + Coquelicot    → RischCoqDischarge.v      (Tier 8.1)
  Isabelle/HOL        → RischIsabelleDischarge.thy  (this module)

Public API
----------
IsabelleProof                   dataclass
emit_isabelle(claim_id)         → IsabelleProof
emit_all_isabelle()             → list[IsabelleProof]
write_isabelle_file(path)       → Path
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from fricas_bridge.proof_discharger import (
    classify_antideriv,
    synthesize_hypotheses,
    _spec_for,
    _ALL_CLAIMS,
    FRICAS_CACHE,
)

_HEADER = """\
(* Auto-generated by ProofForge Ω cross_prover/isabelle_emitter.py
   Library: Isabelle/HOL + Analysis (https://isabelle.in.tum.de/)
   This file is the Isabelle half of the extended cross-prover stack.
   Matching theorems live in RischAutoDischarge.lean and RischCoqDischarge.v. *)

theory RischIsabelleDischarge
  imports Complex_Main \"HOL-Analysis.Analysis\"
begin
"""

_FOOTER = "\nend\n"


@dataclass
class IsabelleProof:
    theorem_name: str           # "isabelle_autodischarge_007"
    claim_id: str
    integrand: str
    antideriv: str
    hypotheses: list[str]       # ["hx: x ≠ 0"]  Isabelle syntax
    statement: str              # full Isabelle lemma declaration
    proof_script: str           # method proof
    antideriv_shape: str

    @property
    def full_text(self) -> str:
        return self.statement + "\n" + self.proof_script + "\n"


# ---------------------------------------------------------------------------
# Expression translator: Lean → Isabelle/HOL
# ---------------------------------------------------------------------------

def _lean_to_isabelle(expr: str, *, rename_bound: bool = False) -> str:
    """Translate a Lean expression to Isabelle/HOL notation."""
    e = expr
    e = re.sub(r"Real\.log", "ln", e)
    e = re.sub(r"Real\.arctan", "arctan", e)
    e = re.sub(r"Real\.sqrt", "sqrt", e)
    e = e.replace("ℝ", "real")
    e = e.replace("≠", "≠")   # same Unicode, fine
    # Lean ^ → Isabelle ^ (same operator, different precedence but fine here)
    if rename_bound:
        e = re.sub(r"\bt\b", "x", e)
    return e


def _isabelle_hypotheses(hyp_objects: list) -> list[str]:
    """Convert Hypothesis objects to Isabelle assumes strings."""
    hyps: list[str] = []
    for h in hyp_objects:
        binder = h.lean_binder.strip("()")
        name, _, stmt = binder.partition(" : ")
        # In Isabelle: assumes "x ≠ 0"
        hyps.append(stmt.strip())
    return hyps


# ---------------------------------------------------------------------------
# Shape-specific proof methods
# ---------------------------------------------------------------------------

def _proof_class_a() -> str:
    return "  by (auto intro!: derivative_eq_intros simp: field_simps)"


def _proof_class_a_trig() -> str:
    return "  by (auto intro!: derivative_eq_intros simp: field_simps add_nonneg_nonneg)"


def _proof_class_b() -> str:
    return "  using hx by (auto intro!: derivative_eq_intros simp: field_simps)"


def _proof_class_c() -> str:
    return "  using hx hx1 by (auto intro!: derivative_eq_intros simp: field_simps)"


def _proof_class_d() -> str:
    return "  using hx hx1 hx2 by (auto intro!: derivative_eq_intros simp: field_simps)"


def _proof_for_shape(shape: str, n_hyps: int) -> str:
    if shape in ("LOG_SIMPLE", "LOG_NEG_QUAD"):
        return _proof_class_b()
    if shape == "LOG_PFD":
        return _proof_class_c() if n_hyps == 2 else _proof_class_d()
    if shape in ("ARCTAN_POW", "ARCTAN_LINEAR", "COMPLEX_SUM"):
        return _proof_class_a_trig()
    return _proof_class_a()


# ---------------------------------------------------------------------------
# Statement builder
# ---------------------------------------------------------------------------

def _build_statement(
    theorem_name: str,
    integrand_isa: str,
    antideriv_isa: str,
    hyp_stmts: list[str],
) -> str:
    lines = [f"lemma {theorem_name}:"]
    for h in hyp_stmts:
        name = f"h{h.split()[0].lower()}" if h.split() else "h"
        lines.append(f'  assumes "{h}"')
    lines.append(f'  shows "(\\<lambda>x. {antideriv_isa}) has_real_derivative ({integrand_isa}) (at x)"')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def emit_isabelle(claim_id: str) -> IsabelleProof:
    """Emit an Isabelle/HOL proof for a named Bronstein claim."""
    spec = _spec_for(claim_id)
    fricas_antideriv = FRICAS_CACHE[claim_id]["antideriv_fricas"]
    suffix = claim_id.split("_")[-1] if "_" in claim_id else claim_id

    shape_dict = classify_antideriv(fricas_antideriv)
    shape = shape_dict.get("shape", "UNKNOWN")
    hyp_objects = synthesize_hypotheses(fricas_antideriv)
    hyp_stmts = _isabelle_hypotheses(hyp_objects)

    antideriv_isa = _lean_to_isabelle(spec.antideriv_body, rename_bound=True)
    integrand_isa = _lean_to_isabelle(spec.integrand_expr)
    proof_script = _proof_for_shape(shape, len(hyp_objects))
    theorem_name = f"isabelle_autodischarge_{suffix}"
    statement = _build_statement(theorem_name, integrand_isa, antideriv_isa, hyp_stmts)

    return IsabelleProof(
        theorem_name=theorem_name,
        claim_id=claim_id,
        integrand=spec.integrand_expr,
        antideriv=spec.antideriv_body,
        hypotheses=hyp_stmts,
        statement=statement,
        proof_script=proof_script,
        antideriv_shape=shape,
    )


def emit_all_isabelle() -> list[IsabelleProof]:
    """Emit Isabelle proofs for all nine Risch–Bronstein claims."""
    return [emit_isabelle(cid) for cid in _ALL_CLAIMS]


def write_isabelle_file(path: Optional[str] = None) -> Path:
    """Write a self-contained .thy file. Returns the Path of the written file."""
    dest = Path(path) if path else Path(__file__).parent / "RischIsabelleDischarge.thy"
    proofs = emit_all_isabelle()
    parts = [_HEADER]
    for p in proofs:
        parts.append(f"\n(* Claim: {p.claim_id} | shape: {p.antideriv_shape} *)")
        parts.append(p.full_text)
    parts.append(_FOOTER)
    dest.write_text("\n".join(parts))
    return dest
