(* Auto-generated by ProofForge Ω cross_prover/coq_emitter.py
   Library: Coquelicot 3.x  (https://coquelicot.saclay.inria.fr/)
   This file is the Coq half of the cross-prover certificate (Tier 8.2).
   Each theorem is independently kernel-checked by Coq; the matching Lean 4
   theorem lives in fricas_bridge/RischAutoDischarge.lean. *)

Require Import Reals Coquelicot.Coquelicot.
Open Scope R_scope.


(* Claim: pf.integral.bronstein_001 | shape: COMPLEX_SUM *)
Theorem coq_autodischarge_001 (x : R) :
  is_derive (fun x => ln (x ^ 2 + 1) ^ 2 / 2 + x ^ 2 / 2 - ln (x ^ 2 + 1) / 2) x ((2 * x * ln (x ^ 2 + 1) + x ^ 3) / (x ^ 2 + 1)).
Proof.
  auto_derive;
    try (apply Rgt_not_eq; lra);
    field_simplify; ring.
Qed.


(* Claim: pf.integral.bronstein_003 | shape: LOG_POS_QUAD *)
Theorem coq_autodischarge_003 (x : R) :
  is_derive (fun x => ln (x ^ 2 + 1) / 2) x (x / (x ^ 2 + 1)).
Proof.
  auto_derive; try ring.
Qed.


(* Claim: pf.integral.bronstein_004 | shape: ARCTAN_POW *)
Theorem coq_autodischarge_004 (x : R) :
  is_derive (fun x => atan (x ^ 2)) x (2 * x / (1 + x ^ 4)).
Proof.
  auto_derive;
    try (apply Rgt_not_eq; lra);
    field_simplify; ring.
Qed.


(* Claim: pf.integral.bronstein_005 | shape: LOG_PFD *)
Theorem coq_autodischarge_005 (x : R) (hx : x <> 0) (hx2 : x + 2 <> 0) :
  is_derive (fun x => ln x / 2 + ln (x + 2) / 2) x ((x + 1) / (x * (x + 2))).
Proof.
  auto_derive;
    [exact hx | exact hx1 | field_simplify [hx hx1]; ring].
Qed.


(* Claim: pf.integral.bronstein_006 | shape: ARCTAN_LINEAR *)
Theorem coq_autodischarge_006 (x : R) :
  is_derive (fun x => atan (x + 1)) x (1 / (x ^ 2 + 2 * x + 2)).
Proof.
  auto_derive;
    try (apply Rgt_not_eq; lra);
    field_simplify; ring.
Qed.


(* Claim: pf.integral.bronstein_007 | shape: LOG_SIMPLE *)
Theorem coq_autodischarge_007 (x : R) (hx : x <> 0) :
  is_derive (fun x => ln x) x (1 / x).
Proof.
  auto_derive; [exact hx | field_simplify; ring].
Qed.


(* Claim: pf.integral.bronstein_008 | shape: LOG_NEG_QUAD *)
Theorem coq_autodischarge_008 (x : R) (hne : (x ^ 2 - 4 : R) <> 0) :
  is_derive (fun x => ln (x ^ 2 - 4) / 2) x (x / (x ^ 2 - 4)).
Proof.
  auto_derive; [exact hx | field_simplify; ring].
Qed.


(* Claim: pf.integral.bronstein_009 | shape: LOG_PFD *)
Theorem coq_autodischarge_009 (x : R) (hx : x <> 0) (hx1 : x + 1 <> 0) (hx2 : x + 2 <> 0) :
  is_derive (fun x => ln x / 2 - ln (x + 1) + ln (x + 2) / 2) x (1 / (x * (x + 1) * (x + 2))).
Proof.
  auto_derive;
    [exact hx | exact hx1 | exact hx2 |
     field_simplify [hx hx1 hx2]; ring].
Qed.


(* end of generated file *)
