(* Auto-generated by ProofForge Ω cross_prover/isabelle_emitter.py
   Library: Isabelle/HOL + Analysis (https://isabelle.in.tum.de/)
   This file is the Isabelle half of the extended cross-prover stack.
   Matching theorems live in RischAutoDischarge.lean and RischCoqDischarge.v. *)

theory RischIsabelleDischarge
  imports Complex_Main "HOL-Analysis.Analysis"
begin


(* Claim: pf.integral.bronstein_001 | shape: COMPLEX_SUM *)
lemma isabelle_autodischarge_001:
  shows "(\<lambda>x. ln (x ^ 2 + 1) ^ 2 / 2 + x ^ 2 / 2 - ln (x ^ 2 + 1) / 2) has_real_derivative ((2 * x * ln (x ^ 2 + 1) + x ^ 3) / (x ^ 2 + 1)) (at x)"
  by (auto intro!: derivative_eq_intros simp: field_simps add_nonneg_nonneg)


(* Claim: pf.integral.bronstein_003 | shape: LOG_POS_QUAD *)
lemma isabelle_autodischarge_003:
  shows "(\<lambda>x. ln (x ^ 2 + 1) / 2) has_real_derivative (x / (x ^ 2 + 1)) (at x)"
  by (auto intro!: derivative_eq_intros simp: field_simps)


(* Claim: pf.integral.bronstein_004 | shape: ARCTAN_POW *)
lemma isabelle_autodischarge_004:
  shows "(\<lambda>x. arctan (x ^ 2)) has_real_derivative (2 * x / (1 + x ^ 4)) (at x)"
  by (auto intro!: derivative_eq_intros simp: field_simps add_nonneg_nonneg)


(* Claim: pf.integral.bronstein_005 | shape: LOG_PFD *)
lemma isabelle_autodischarge_005:
  assumes "x ≠ 0"
  assumes "x + 2 ≠ 0"
  shows "(\<lambda>x. ln x / 2 + ln (x + 2) / 2) has_real_derivative ((x + 1) / (x * (x + 2))) (at x)"
  using hx hx1 by (auto intro!: derivative_eq_intros simp: field_simps)


(* Claim: pf.integral.bronstein_006 | shape: ARCTAN_LINEAR *)
lemma isabelle_autodischarge_006:
  shows "(\<lambda>x. arctan (x + 1)) has_real_derivative (1 / (x ^ 2 + 2 * x + 2)) (at x)"
  by (auto intro!: derivative_eq_intros simp: field_simps add_nonneg_nonneg)


(* Claim: pf.integral.bronstein_007 | shape: LOG_SIMPLE *)
lemma isabelle_autodischarge_007:
  assumes "x ≠ 0"
  shows "(\<lambda>x. ln x) has_real_derivative (1 / x) (at x)"
  using hx by (auto intro!: derivative_eq_intros simp: field_simps)


(* Claim: pf.integral.bronstein_008 | shape: LOG_NEG_QUAD *)
lemma isabelle_autodischarge_008:
  assumes "(x ^ 2 - 4 : ℝ) ≠ 0"
  shows "(\<lambda>x. ln (x ^ 2 - 4) / 2) has_real_derivative (x / (x ^ 2 - 4)) (at x)"
  using hx by (auto intro!: derivative_eq_intros simp: field_simps)


(* Claim: pf.integral.bronstein_009 | shape: LOG_PFD *)
lemma isabelle_autodischarge_009:
  assumes "x ≠ 0"
  assumes "x + 1 ≠ 0"
  assumes "x + 2 ≠ 0"
  shows "(\<lambda>x. ln x / 2 - ln (x + 1) + ln (x + 2) / 2) has_real_derivative (1 / (x * (x + 1) * (x + 2))) (at x)"
  using hx hx1 hx2 by (auto intro!: derivative_eq_intros simp: field_simps)


end
