-- Auto-generated by spad2lean.py
-- FriCAS category hierarchy → Lean 4 typeclasses
-- Sources: catdef.spad · naalgc.spad · logic.spad

-- ────────────────────────────────────────────────────────────────────
-- AbelianGroup  [ABELGRP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class AbelianGroup (α : Type*) extends CancellationAbelianMonoid α where
  neg : α → α
  sub : α → α → α
  mul : Int → α → α

  ax0 : ∀ x : α, (neg (neg x)) = x
  ax1 : ∀ x : α, (add x (neg x)) = 0

-- ────────────────────────────────────────────────────────────────────
-- AbelianMonoid  [ABELMON]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class AbelianMonoid (α : Type*) extends AbelianSemiGroup α where
  zero : α
  zero_ : α → Bool
  mul : Nat → α → α
  opposite_ : α → α → Bool

  ax0 : ∀ x : α, (add 0 x) = x
  ax1 : ∀ x : α, (add x 0) = x

-- ────────────────────────────────────────────────────────────────────
-- AbelianSemiGroup  [ABELSG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class AbelianSemiGroup (α : Type*) extends SetCategory α where
  add : α → α → α
  mul : PosNat → α → α

  ax0 : ∀ x y z : α, (add (add x y) z) = (add x (add y z))
  ax1 : ∀ x y : α, (add x y) = (add y x)

-- ────────────────────────────────────────────────────────────────────
-- Algebra  [ALGEBRA]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Algebra (R : CommutativeRing) (α : Type*) extends Ring α, NonAssociativeAlgebra R α where
  coerce : R → α

  ax0 : ∀ a b r : α, (mul r (mul a b)) = (mul (mul r a) b)
  ax1 : ∀ a b r : α, (mul (mul a b) r) = (mul a (mul b r))

-- ────────────────────────────────────────────────────────────────────
-- BasicType  [BASTYPE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class BasicType (α : Type*) where
  eq : α → α → Bool
  ne : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- BiModule  [BMODULE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class BiModule (R : SemiRng) (S : SemiRng) (α : Type*) extends LeftModule R α, RightModule S α where
  -- (no new operations beyond inherited)

  ax0 : ∀ r s x : α, (mul r (mul x s)) = (mul (mul r x) s)

-- ────────────────────────────────────────────────────────────────────
-- CancellationAbelianMonoid  [CABMON]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class CancellationAbelianMonoid (α : Type*) extends AbelianMonoid α where
  subtractIfCan : α → α → Option α

  -- (informal) c = a+b <=> c-b = a

-- ────────────────────────────────────────────────────────────────────
-- CharacteristicNonZero  [CHARNZ]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class CharacteristicNonZero (α : Type*) extends Ring α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- CharacteristicZero  [CHARZ]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class CharacteristicZero (α : Type*) extends Ring α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- CommutativeRing  [COMRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class CommutativeRing (α : Type*) extends Ring α, Algebra α α, CommutativeStar α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- DifferentialRing  [DIFRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class DifferentialRing (α : Type*) extends Ring α where
  differentiate : α → α
  D : α → α

  ax0 : ∀ x y : α, (differentiate (add x y)) = (add (differentiate x) (differentiate y))
  ax1 : ∀ x y : α, (differentiate (mul x y)) = (add (mul x (differentiate y)) (mul (differentiate x) y))

-- ────────────────────────────────────────────────────────────────────
-- DivisionRing  [DIVRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class DivisionRing (α : Type*) extends EntireRing α, TwoSidedRecip α where
  pow : α → Int → α
  inv : α → α

-- ────────────────────────────────────────────────────────────────────
-- EntireRing  [ENTIRER]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class EntireRing (α : Type*) extends Ring α where
  exquo : α → α → Option α
  unitNormal : α → Record_
  unitCanonical : α → α
  associates_ : α → α → Bool
  unit_ : α → Bool

  -- (informal) not(1=0)

-- ────────────────────────────────────────────────────────────────────
-- EuclideanDomain  [EUCDOM]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class EuclideanDomain (α : Type*) extends PrincipalIdealDomain α where
  sizeLess_ : α → α → Bool
  euclideanSize : α → Nat
  divide : α → α → Record_
  quot : α → α → α
  rem_op : α → α → α
  extendedEuclidean : α → α → Record_
  multiEuclidean : List α → α → Option _

-- ────────────────────────────────────────────────────────────────────
-- Field  [FIELD]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Field (α : Type*) extends EuclideanDomain α, UniqueFactorizationDomain α, DivisionRing α where
  div : α → α → α
  inv : α → α

  ax0 : ∀ a b : α, (mul a (div b a)) = b
  ax1 : ∀ a : α, (inv a) = (div 1 a)

-- ────────────────────────────────────────────────────────────────────
-- Finite  [FINITE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Finite (α : Type*) extends SetCategory α, Comparable α, Hashable α where
  size : Nat
  index : PosNat → α
  lookup : α → PosNat
  random : α
  enumerate : List α

  ax0 : ∀ n : α, (lookup (index n)) = n
  ax1 : ∀ s : α, (index (lookup s)) = s

-- ────────────────────────────────────────────────────────────────────
-- GcdDomain  [GCDDOM]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class GcdDomain (α : Type*) extends IntegralDomain α, LeftOreRing α where
  gcd : α → α → α
  lcm : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- Group  [GROUP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Group (α : Type*) extends Monoid α, TwoSidedRecip α where
  inv : α → α
  div : α → α → α
  pow : α → Int → α
  conjugate : α → α → α
  commutator : α → α → α

  ax0 : ∀ x : α, (mul (inv x) x) = 1
  ax1 : ∀ x : α, (mul x (inv x)) = 1

-- ────────────────────────────────────────────────────────────────────
-- IntegralDomain  [INTDOM]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class IntegralDomain (α : Type*) extends CommutativeRing α, EntireRing α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- LeftModule  [LMODULE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class LeftModule (R : SemiRng) (α : Type*) extends AbelianSemiGroup α where
  mul : R → α → α

  ax0 : ∀ a b x : α, (mul (mul a b) x) = (mul a (mul b x))
  ax1 : ∀ a b x : α, (mul (add a b) x) = (add (mul a x) (mul b x))
  ax2 : ∀ a x y : α, (mul a (add x y)) = (add (mul a x) (mul a y))

-- ────────────────────────────────────────────────────────────────────
-- LeftOreRing  [LORER]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class LeftOreRing (α : Type*) extends EntireRing α where
  lcmCoef : α → α → Record_

-- ────────────────────────────────────────────────────────────────────
-- Magma  [MAGMA]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Magma (α : Type*) where
  mul : α → α → α
  pow : α → PosNat → α

-- ────────────────────────────────────────────────────────────────────
-- MagmaWithUnit  [MAGMAWU]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class MagmaWithUnit (α : Type*) extends Magma α where
  one : α
  one_ : α → Bool
  recip : α → Option α
  pow : α → Nat → α

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ x : α, (mul x 1) = x

-- ────────────────────────────────────────────────────────────────────
-- Module  [MODULE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Module (R : CommutativeRing) (α : Type*) extends BiModule R R α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ a b x : α, (mul (mul a b) x) = (mul a (mul b x))
  ax2 : ∀ a b x : α, (mul (add a b) x) = (add (mul a x) (mul b x))
  ax3 : ∀ a x y : α, (mul a (add x y)) = (add (mul a x) (mul a y))

-- ────────────────────────────────────────────────────────────────────
-- Monoid  [MONOID]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Monoid (α : Type*) extends SemiGroup α, MagmaWithUnit α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ x : α, (mul x 1) = x

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeAlgebra  [NAALG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeAlgebra (R : CommutativeRing) (α : Type*) extends NonAssociativeRng α, Module R α where
  -- (no new operations beyond inherited)

  ax0 : ∀ a b r : α, (mul r (mul a b)) = (mul (mul r a) b)

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeRng  [NARNG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeRng (α : Type*) extends NonAssociativeSemiRng α, AbelianGroup α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y z : α, (mul x (add y z)) = (add (mul x y) (mul x z))
  ax1 : ∀ x y z : α, (mul (add x y) z) = (add (mul x z) (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeRing  [NARING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeRing (α : Type*) extends NonAssociativeRng α, NonAssociativeSemiRing α where
  characteristic : Nat
  coerce : Int → α

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeSemiRng  [NASRNG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeSemiRng (α : Type*) extends AbelianSemiGroup α, Magma α where
  antiCommutator : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeSemiRing  [NASRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeSemiRing (α : Type*) extends NonAssociativeSemiRng α, AbelianMonoid α, MagmaWithUnit α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianGroup  [OAGROUP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianGroup (α : Type*) extends OrderedCancellationAbelianMonoid α, AbelianGroup α where
  positive_ : α → Bool
  negative_ : α → Bool
  sign : α → Int
  abs : α → α

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianMonoid  [OAMON]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianMonoid (α : Type*) extends OrderedAbelianSemiGroup α, AbelianMonoid α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- OrderedCancellationAbelianMonoid  [OCAMON]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedCancellationAbelianMonoid (α : Type*) extends OrderedAbelianMonoid α, CancellationAbelianMonoid α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- OrderedMonoid  [ORDMON]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedMonoid (α : Type*) extends OrderedSemiGroup α, Monoid α where
  -- (no new operations beyond inherited)

  -- (informal) x < y => x*z < y*z
  -- (informal) x < y => z*x < z*y

-- ────────────────────────────────────────────────────────────────────
-- OrderedRing  [ORDRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedRing (α : Type*) extends OrderedAbelianGroup α, OrderedMonoid α, Ring α, CharacteristicZero α where
  -- (no new operations beyond inherited)

  -- (informal) 0<a and 0<b => 0 < a*b

-- ────────────────────────────────────────────────────────────────────
-- OrderedSet  [ORDSET]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedSet (α : Type*) extends Comparable α, PartialOrder α where
  max : α → α → α
  min : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianSemiGroup  [OASGP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianSemiGroup (α : Type*) extends OrderedSet α, AbelianSemiGroup α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- OrderedSemiGroup  [OSGROUP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedSemiGroup (α : Type*) extends OrderedSet α, SemiGroup α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- PartialOrder  [PORDER]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class PartialOrder (α : Type*) where
  lt : α → α → Bool
  gt : α → α → Bool
  ge : α → α → Bool
  le : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- PartialDifferentialRing  [PDRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class PartialDifferentialRing (S : SetCategory) (α : Type*) extends Ring α where
  differentiate : α → S → α
  D : α → S → α

  ax0 : ∀ e x y : α, (differentiate (add x y) e) = (add (differentiate x e) (differentiate y e))
  ax1 : ∀ e x y : α, (differentiate (mul x y) e) = (add (mul x (differentiate y e)) (mul (differentiate x e) y))

-- ────────────────────────────────────────────────────────────────────
-- PrincipalIdealDomain  [PID]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class PrincipalIdealDomain (α : Type*) extends GcdDomain α where
  principalIdeal : List α → Record_
  expressIdealMember : List α → α → Option _

-- ────────────────────────────────────────────────────────────────────
-- Comparable  [COMPAR]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Comparable (α : Type*) extends SetCategory α where
  smaller_ : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- RightModule  [RMODULE]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class RightModule (R : SemiRng) (α : Type*) extends AbelianSemiGroup α where
  mul : α → R → α

  ax0 : ∀ a b x : α, (mul x (mul a b)) = (mul (mul x a) b)
  ax1 : ∀ a b x : α, (mul x (add a b)) = (add (mul x a) (mul x b))
  ax2 : ∀ a x y : α, (mul (add x y) a) = (add (mul x a) (mul y a))

-- ────────────────────────────────────────────────────────────────────
-- Ring  [RING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Ring (α : Type*) extends Rng α, SemiRing α, NonAssociativeRing α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- SemiRng  [SRNG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class SemiRng (α : Type*) extends NonAssociativeSemiRng α, BiModule α α α, SemiGroup α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- SemiRing  [SRING]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class SemiRing (α : Type*) extends NonAssociativeSemiRing α, SemiRng α, Monoid α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- Rng  [RNG]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Rng (α : Type*) extends NonAssociativeRng α, SemiRng α where
  annihilate_ : α → α → Bool

  ax0 : ∀ x y z : α, (mul x (add y z)) = (add (mul x y) (mul x z))
  ax1 : ∀ x y z : α, (mul (add x y) z) = (add (mul x z) (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- SemiGroup  [SGROUP]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class SemiGroup (α : Type*) extends Magma α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y z : α, (mul (mul x y) z) = (mul x (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- Hashable  [HASHABL]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class Hashable (α : Type*) extends BasicType α where
  hash : α → Int
  hashUpdate_ : HashState → α → HashState

-- ────────────────────────────────────────────────────────────────────
-- SetCategory  [SETCAT]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class SetCategory (α : Type*) extends BasicType α, CoercibleTo OutputForm α where
  latex : α → String

-- ────────────────────────────────────────────────────────────────────
-- UniqueFactorizationDomain  [UFD]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class UniqueFactorizationDomain (α : Type*) extends GcdDomain α where
  prime_ : α → Bool
  squareFree : α → Factored(α)
  squareFreePart : α → α
  factor : α → Factored(α)

-- ────────────────────────────────────────────────────────────────────
-- OrderedIntegralDomain  [OINTDOM]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedIntegralDomain (α : Type*) extends IntegralDomain α, OrderedRing α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- OrderedFinite  [ORDFIN]  [catdef.spad]
-- ────────────────────────────────────────────────────────────────────
class OrderedFinite (α : Type*) extends OrderedSet α, Finite α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- FiniteRankNonAssociativeAlgebra  [FINAALG]  [naalgc.spad]
-- ────────────────────────────────────────────────────────────────────
class FiniteRankNonAssociativeAlgebra (R : CommutativeRing) (α : Type*) extends NonAssociativeAlgebra R α where
  rank : PosNat
  someBasis : Vector α
  structuralConstants : Vector α → Vector Matrix R
  coordinates : α → Vector α → Vector R
  represents : Vector R → Vector α → α
  leftTrace : α → R
  rightTrace : α → R
  leftNorm : α → R
  rightNorm : α → R
  commutative_ : Bool
  associative_ : Bool
  jacobiIdentity_ : Bool
  lieAlgebra_ : Bool
  jordanAlgebra_ : Bool

-- ────────────────────────────────────────────────────────────────────
-- FramedNonAssociativeAlgebra  [FRNAALG]  [naalgc.spad]
-- ────────────────────────────────────────────────────────────────────
class FramedNonAssociativeAlgebra (R : CommutativeRing) (α : Type*) extends FiniteRankNonAssociativeAlgebra R α, FramedModule R α where
  elt : α → Int → R
  structuralConstants : Vector Matrix R
  conditionsForIdempotents : List Polynomial R
  leftDiscriminant : R
  rightDiscriminant : R

-- ────────────────────────────────────────────────────────────────────
-- MeetSemilattice  [MEETLAT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class MeetSemilattice (α : Type*) extends SetCategory α where
  meet : α → α → α

  ax0 : ∀ x : α, (meet x x) = x
  ax1 : ∀ x y : α, (meet x y) = (meet y x)
  ax2 : ∀ x y z : α, (meet (meet x y) z) = (meet x (meet y z))

-- ────────────────────────────────────────────────────────────────────
-- BoundedMeetSemilattice  [BMEET]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class BoundedMeetSemilattice (α : Type*) extends MeetSemilattice α where
  top : α

  ax0 : ∀ x : α, (meet x top) = x

-- ────────────────────────────────────────────────────────────────────
-- JoinSemilattice  [JOINLAT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class JoinSemilattice (α : Type*) extends SetCategory α where
  join : α → α → α

  ax0 : ∀ x : α, (join x x) = x
  ax1 : ∀ x y : α, (join x y) = (join y x)
  ax2 : ∀ x y z : α, (join (join x y) z) = (join x (join y z))

-- ────────────────────────────────────────────────────────────────────
-- BoundedJoinSemilattice  [BJOIN]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class BoundedJoinSemilattice (α : Type*) extends JoinSemilattice α where
  bot : α

  ax0 : ∀ x : α, (join x bot) = x

-- ────────────────────────────────────────────────────────────────────
-- Lattice  [LAT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class Lattice (α : Type*) extends MeetSemilattice α, JoinSemilattice α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y : α, (meet x (join x y)) = x
  ax1 : ∀ x y : α, (join x (meet x y)) = x

-- ────────────────────────────────────────────────────────────────────
-- BoundedLattice  [BLAT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class BoundedLattice (α : Type*) extends BoundedMeetSemilattice α, BoundedJoinSemilattice α where
  -- (no new operations beyond inherited)

-- ────────────────────────────────────────────────────────────────────
-- DistributiveLattice  [DISTLAT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class DistributiveLattice (α : Type*) extends Lattice α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y z : α, (meet x (join y z)) = (join (meet x y) (meet x z))
  ax1 : ∀ x y z : α, (join x (meet y z)) = (meet (join x y) (join x z))

-- ────────────────────────────────────────────────────────────────────
-- BoundedDistributiveLattice  [BDISTL]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class BoundedDistributiveLattice (α : Type*) extends BoundedLattice α, DistributiveLattice α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y z : α, (meet x (join y z)) = (join (meet x y) (meet x z))
  ax1 : ∀ x y z : α, (join x (meet y z)) = (meet (join x y) (join x z))

-- ────────────────────────────────────────────────────────────────────
-- Logic  [LOGIC]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class Logic (α : Type*) extends BoundedDistributiveLattice α where
  true_val : α
  false_val : α
  lnot : α → α

  ax0 : ∀ x : α, (meet x (lnot x)) = bot
  ax1 : ∀ x : α, (join x (lnot x)) = top

-- ────────────────────────────────────────────────────────────────────
-- Preorder  [PREORD]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class Preorder (α : Type*) extends SetCategory α where
  leq : α → α → Bool
  geq : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- Poset  [POSET]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class Poset (α : Type*) extends Preorder α where
  minElt : α → α → α
  maxElt : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- TotalOrder  [TOSET]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class TotalOrder (α : Type*) extends Poset α where
  -- (no new operations beyond inherited)

  ax0 : ∀ x y : α, (leq x y) = (leq y x)

-- ────────────────────────────────────────────────────────────────────
-- CompleteLattic  [COMPLT]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class CompleteLattic (α : Type*) extends BoundedLattice α where
  sup : α → α → α
  inf : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- BooleanRing  [BOOLRING]  [logic.spad]
-- ────────────────────────────────────────────────────────────────────
class BooleanRing (α : Type*) extends CommutativeRing α, BoundedDistributiveLattice α where
  xor : α → α → α

  ax0 : ∀ x : α, (mul x x) = x
