-- Auto-generated by spad2lean.py
-- FriCAS category hierarchy → Lean 4 typeclasses
-- Source: fricas/fricas src/algebra/catdef.spad

-- ────────────────────────────────────────────────────────────────────
-- AbelianGroup  [ABELGRP]
-- ────────────────────────────────────────────────────────────────────
class AbelianGroup (α : Type*) extends CancellationAbelianMonoid where
  neg : α → α
  sub : α → α → α
  mul : Int → α → α

  ax0 : ∀ x : α, (neg (neg x)) = x
  ax1 : ∀ x : α, (add x (neg x)) = 0

-- ────────────────────────────────────────────────────────────────────
-- AbelianMonoid  [ABELMON]
-- ────────────────────────────────────────────────────────────────────
class AbelianMonoid (α : Type*) extends AbelianSemiGroup where
  zero_ : α → Bool
  mul : Nat → α → α
  opposite_ : α → α → Bool

  ax0 : ∀ x : α, (add 0 x) = x
  ax1 : ∀ x : α, (add x 0) = x

-- ────────────────────────────────────────────────────────────────────
-- AbelianSemiGroup  [ABELSG]
-- ────────────────────────────────────────────────────────────────────
class AbelianSemiGroup (α : Type*) extends SetCategory where
  add : α → α → α
  mul : PosNat → α → α

  ax0 : ∀ x y z : α, (add (add x y) z) = (add x (add y z))
  ax1 : ∀ x y : α, (add x y) = (add y x)

-- ────────────────────────────────────────────────────────────────────
-- Algebra  [ALGEBRA]
-- ────────────────────────────────────────────────────────────────────
class Algebra (R : CommutativeRing) (α : Type*) extends Ring, NonAssociativeAlgebra R where
  coerce : R → α

  ax0 : ∀ a b r : α, (mul r (mul a b)) = (mul (mul r a) b)
  ax1 : ∀ a b r : α, (mul (mul a b) r) = (mul a (mul b r))

-- ────────────────────────────────────────────────────────────────────
-- BasicType  [BASTYPE]
-- ────────────────────────────────────────────────────────────────────
class BasicType (α : Type*) where
  eq : α → α → Bool
  ne : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- BiModule  [BMODULE]
-- ────────────────────────────────────────────────────────────────────
class BiModule (R : SemiRng) (S : SemiRng) (α : Type*) extends LeftModule R, RightModule S where
  -- (no new operations)

  ax0 : ∀ r s x : α, (mul r (mul x s)) = (mul (mul r x) s)

-- ────────────────────────────────────────────────────────────────────
-- CancellationAbelianMonoid  [CABMON]
-- ────────────────────────────────────────────────────────────────────
class CancellationAbelianMonoid (α : Type*) extends AbelianMonoid where
  subtractIfCan : α → α → Option α

  -- (informal) c = a+b <=> c-b = a

-- ────────────────────────────────────────────────────────────────────
-- CharacteristicNonZero  [CHARNZ]
-- ────────────────────────────────────────────────────────────────────
class CharacteristicNonZero (α : Type*) extends Ring where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- CharacteristicZero  [CHARZ]
-- ────────────────────────────────────────────────────────────────────
class CharacteristicZero (α : Type*) extends Ring where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- CommutativeRing  [COMRING]
-- ────────────────────────────────────────────────────────────────────
class CommutativeRing (α : Type*) extends Ring, Algebra α, CommutativeStar where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- DifferentialRing  [DIFRING]
-- ────────────────────────────────────────────────────────────────────
class DifferentialRing (α : Type*) extends Ring where
  differentiate : α → α
  D : α → α

  ax0 : ∀ x y : α, (differentiate (add x y)) = (add (differentiate x) (differentiate y))
  ax1 : ∀ x y : α, (differentiate (mul x y)) = (add (mul x (differentiate y)) (mul (differentiate x) y))

-- ────────────────────────────────────────────────────────────────────
-- DivisionRing  [DIVRING]
-- ────────────────────────────────────────────────────────────────────
class DivisionRing (α : Type*) extends EntireRing, TwoSidedRecip where
  pow : α → Int → α
  inv : α → α

-- ────────────────────────────────────────────────────────────────────
-- EntireRing  [ENTIRER]
-- ────────────────────────────────────────────────────────────────────
class EntireRing (α : Type*) extends Ring where
  exquo : α → α → Option α
  unitNormal : α → Record_
  unitCanonical : α → α
  associates_ : α → α → Bool
  unit_ : α → Bool

  -- (informal) not(1=0)

-- ────────────────────────────────────────────────────────────────────
-- EuclideanDomain  [EUCDOM]
-- ────────────────────────────────────────────────────────────────────
class EuclideanDomain (α : Type*) extends PrincipalIdealDomain where
  sizeLess_ : α → α → Bool
  euclideanSize : α → Nat
  divide : α → α → Record_
  quot : α → α → α
  rem_op : α → α → α
  extendedEuclidean : α → α → Record_
  multiEuclidean : List α → α → Option _

-- ────────────────────────────────────────────────────────────────────
-- Field  [FIELD]
-- ────────────────────────────────────────────────────────────────────
class Field (α : Type*) extends EuclideanDomain, UniqueFactorizationDomain, DivisionRing where
  div : α → α → α
  inv : α → α

  ax0 : ∀ a b : α, (mul a (div b a)) = b
  ax1 : ∀ a : α, (inv a) = (div 1 a)

-- ────────────────────────────────────────────────────────────────────
-- Finite  [FINITE]
-- ────────────────────────────────────────────────────────────────────
class Finite (α : Type*) extends SetCategory, Comparable, Hashable where
  size : Nat
  index : PosNat → α
  lookup : α → PosNat
  random : α
  enumerate : List α

  ax0 : ∀ n : α, (lookup (index n)) = n
  ax1 : ∀ s : α, (index (lookup s)) = s

-- ────────────────────────────────────────────────────────────────────
-- GcdDomain  [GCDDOM]
-- ────────────────────────────────────────────────────────────────────
class GcdDomain (α : Type*) extends IntegralDomain, LeftOreRing where
  gcd : α → α → α
  lcm : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- Group  [GROUP]
-- ────────────────────────────────────────────────────────────────────
class Group (α : Type*) extends Monoid, TwoSidedRecip where
  inv : α → α
  div : α → α → α
  pow : α → Int → α
  conjugate : α → α → α
  commutator : α → α → α

  ax0 : ∀ x : α, (mul (inv x) x) = 1
  ax1 : ∀ x : α, (mul x (inv x)) = 1

-- ────────────────────────────────────────────────────────────────────
-- IntegralDomain  [INTDOM]
-- ────────────────────────────────────────────────────────────────────
class IntegralDomain (α : Type*) extends CommutativeRing, EntireRing where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- LeftModule  [LMODULE]
-- ────────────────────────────────────────────────────────────────────
class LeftModule (R : SemiRng) (α : Type*) extends AbelianSemiGroup where
  mul : R → α → α

  ax0 : ∀ a b x : α, (mul (mul a b) x) = (mul a (mul b x))
  ax1 : ∀ a b x : α, (mul (add a b) x) = (add (mul a x) (mul b x))
  ax2 : ∀ a x y : α, (mul a (add x y)) = (add (mul a x) (mul a y))

-- ────────────────────────────────────────────────────────────────────
-- LeftOreRing  [LORER]
-- ────────────────────────────────────────────────────────────────────
class LeftOreRing (α : Type*) extends EntireRing where
  lcmCoef : α → α → Record_

-- ────────────────────────────────────────────────────────────────────
-- Magma  [MAGMA]
-- ────────────────────────────────────────────────────────────────────
class Magma (α : Type*) where
  mul : α → α → α
  pow : α → PosNat → α

-- ────────────────────────────────────────────────────────────────────
-- MagmaWithUnit  [MAGMAWU]
-- ────────────────────────────────────────────────────────────────────
class MagmaWithUnit (α : Type*) extends Magma where
  one_ : α → Bool
  recip : α → Option α
  pow : α → Nat → α

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ x : α, (mul x 1) = x

-- ────────────────────────────────────────────────────────────────────
-- Module  [MODULE]
-- ────────────────────────────────────────────────────────────────────
class Module (R : CommutativeRing) (α : Type*) extends BiModule R R where
  -- (no new operations)

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ a b x : α, (mul (mul a b) x) = (mul a (mul b x))
  ax2 : ∀ a b x : α, (mul (add a b) x) = (add (mul a x) (mul b x))
  ax3 : ∀ a x y : α, (mul a (add x y)) = (add (mul a x) (mul a y))

-- ────────────────────────────────────────────────────────────────────
-- Monoid  [MONOID]
-- ────────────────────────────────────────────────────────────────────
class Monoid (α : Type*) extends SemiGroup, MagmaWithUnit where
  -- (no new operations)

  ax0 : ∀ x : α, (mul 1 x) = x
  ax1 : ∀ x : α, (mul x 1) = x

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeAlgebra  [NAALG]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeAlgebra (R : CommutativeRing) (α : Type*) extends NonAssociativeRng, Module R where
  -- (no new operations)

  ax0 : ∀ a b r : α, (mul r (mul a b)) = (mul (mul r a) b)

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeRng  [NARNG]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeRng (α : Type*) extends NonAssociativeSemiRng, AbelianGroup where
  -- (no new operations)

  ax0 : ∀ x y z : α, (mul x (add y z)) = (add (mul x y) (mul x z))
  ax1 : ∀ x y z : α, (mul (add x y) z) = (add (mul x z) (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeRing  [NARING]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeRing (α : Type*) extends NonAssociativeRng, NonAssociativeSemiRing where
  characteristic : Nat
  coerce : Int → α

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeSemiRng  [NASRNG]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeSemiRng (α : Type*) extends AbelianSemiGroup, Magma where
  antiCommutator : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- NonAssociativeSemiRing  [NASRING]
-- ────────────────────────────────────────────────────────────────────
class NonAssociativeSemiRing (α : Type*) extends NonAssociativeSemiRng, AbelianMonoid, MagmaWithUnit where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianGroup  [OAGROUP]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianGroup (α : Type*) extends OrderedCancellationAbelianMonoid, AbelianGroup where
  positive_ : α → Bool
  negative_ : α → Bool
  sign : α → Int
  abs : α → α

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianMonoid  [OAMON]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianMonoid (α : Type*) extends OrderedAbelianSemiGroup, AbelianMonoid where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- OrderedCancellationAbelianMonoid  [OCAMON]
-- ────────────────────────────────────────────────────────────────────
class OrderedCancellationAbelianMonoid (α : Type*) extends OrderedAbelianMonoid, CancellationAbelianMonoid where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- OrderedMonoid  [ORDMON]
-- ────────────────────────────────────────────────────────────────────
class OrderedMonoid (α : Type*) extends OrderedSemiGroup, Monoid where
  -- (no new operations)

  -- (informal) x < y => x*z < y*z
  -- (informal) x < y => z*x < z*y

-- ────────────────────────────────────────────────────────────────────
-- OrderedRing  [ORDRING]
-- ────────────────────────────────────────────────────────────────────
class OrderedRing (α : Type*) extends OrderedAbelianGroup, OrderedMonoid, Ring, CharacteristicZero where
  -- (no new operations)

  -- (informal) 0<a and 0<b => 0 < a*b

-- ────────────────────────────────────────────────────────────────────
-- OrderedSet  [ORDSET]
-- ────────────────────────────────────────────────────────────────────
class OrderedSet (α : Type*) extends Comparable, PartialOrder where
  max : α → α → α
  min : α → α → α

-- ────────────────────────────────────────────────────────────────────
-- OrderedAbelianSemiGroup  [OASGP]
-- ────────────────────────────────────────────────────────────────────
class OrderedAbelianSemiGroup (α : Type*) extends OrderedSet, AbelianSemiGroup where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- OrderedSemiGroup  [OSGROUP]
-- ────────────────────────────────────────────────────────────────────
class OrderedSemiGroup (α : Type*) extends OrderedSet, SemiGroup where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- PartialOrder  [PORDER]
-- ────────────────────────────────────────────────────────────────────
class PartialOrder (α : Type*) where
  lt : α → α → Bool
  gt : α → α → Bool
  ge : α → α → Bool
  le : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- PartialDifferentialRing  [PDRING]
-- ────────────────────────────────────────────────────────────────────
class PartialDifferentialRing (S : SetCategory) (α : Type*) extends Ring where
  differentiate : α → S → α
  D : α → S → α

  ax0 : ∀ e x y : α, (differentiate (add x y) e) = (add (differentiate x e) (differentiate y e))
  ax1 : ∀ e x y : α, (differentiate (mul x y) e) = (add (mul x (differentiate y e)) (mul (differentiate x e) y))

-- ────────────────────────────────────────────────────────────────────
-- PrincipalIdealDomain  [PID]
-- ────────────────────────────────────────────────────────────────────
class PrincipalIdealDomain (α : Type*) extends GcdDomain where
  principalIdeal : List α → Record_
  expressIdealMember : List α → α → Option _

-- ────────────────────────────────────────────────────────────────────
-- Comparable  [COMPAR]
-- ────────────────────────────────────────────────────────────────────
class Comparable (α : Type*) extends SetCategory where
  smaller_ : α → α → Bool

-- ────────────────────────────────────────────────────────────────────
-- RightModule  [RMODULE]
-- ────────────────────────────────────────────────────────────────────
class RightModule (R : SemiRng) (α : Type*) extends AbelianSemiGroup where
  mul : α → R → α

  ax0 : ∀ a b x : α, (mul x (mul a b)) = (mul (mul x a) b)
  ax1 : ∀ a b x : α, (mul x (add a b)) = (add (mul x a) (mul x b))
  ax2 : ∀ a x y : α, (mul (add x y) a) = (add (mul x a) (mul y a))

-- ────────────────────────────────────────────────────────────────────
-- Ring  [RING]
-- ────────────────────────────────────────────────────────────────────
class Ring (α : Type*) extends Rng, SemiRing, NonAssociativeRing where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- SemiRng  [SRNG]
-- ────────────────────────────────────────────────────────────────────
class SemiRng (α : Type*) extends NonAssociativeSemiRng, BiModule α α, SemiGroup where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- SemiRing  [SRING]
-- ────────────────────────────────────────────────────────────────────
class SemiRing (α : Type*) extends NonAssociativeSemiRing, SemiRng, Monoid where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- Rng  [RNG]
-- ────────────────────────────────────────────────────────────────────
class Rng (α : Type*) extends NonAssociativeRng, SemiRng where
  annihilate_ : α → α → Bool

  ax0 : ∀ x y z : α, (mul x (add y z)) = (add (mul x y) (mul x z))
  ax1 : ∀ x y z : α, (mul (add x y) z) = (add (mul x z) (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- SemiGroup  [SGROUP]
-- ────────────────────────────────────────────────────────────────────
class SemiGroup (α : Type*) extends Magma where
  -- (no new operations)

  ax0 : ∀ x y z : α, (mul (mul x y) z) = (mul x (mul y z))

-- ────────────────────────────────────────────────────────────────────
-- Hashable  [HASHABL]
-- ────────────────────────────────────────────────────────────────────
class Hashable (α : Type*) extends BasicType where
  hash : α → Int
  hashUpdate_ : HashState → α → HashState

-- ────────────────────────────────────────────────────────────────────
-- SetCategory  [SETCAT]
-- ────────────────────────────────────────────────────────────────────
class SetCategory (α : Type*) extends BasicType, CoercibleTo OutputForm where
  latex : α → String

-- ────────────────────────────────────────────────────────────────────
-- UniqueFactorizationDomain  [UFD]
-- ────────────────────────────────────────────────────────────────────
class UniqueFactorizationDomain (α : Type*) extends GcdDomain where
  prime_ : α → Bool
  squareFree : α → Factored(α)
  squareFreePart : α → α
  factor : α → Factored(α)

-- ────────────────────────────────────────────────────────────────────
-- OrderedIntegralDomain  [OINTDOM]
-- ────────────────────────────────────────────────────────────────────
class OrderedIntegralDomain (α : Type*) extends IntegralDomain, OrderedRing where
  -- (no new operations)

-- ────────────────────────────────────────────────────────────────────
-- OrderedFinite  [ORDFIN]
-- ────────────────────────────────────────────────────────────────────
class OrderedFinite (α : Type*) extends OrderedSet, Finite where
  -- (no new operations)
