"""
Lean 4 theorem stub generator.

Given a corpus entry dict (conforming to cas_protocol/schema.json), emits a
``.lean`` file containing:
  - A noncomputable function for the antiderivative
  - A theorem stub asserting ``HasDerivAt antideriv integrand x``
  - Hypothesis parameters for every required_hypothesis

Usage:
    from backbone.cas_protocol.lean_emitter import emit_lean_file

    lean_src = emit_lean_file(entry)
    Path("Verify.lean").write_text(lean_src)
"""
from __future__ import annotations

from typing import Any

from backbone.cas_protocol.normalize import fricas_to_lean


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

_FILE_TEMPLATE = """\
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv

open Real

-- Generated by backbone/cas_protocol/lean_emitter.py
-- Source: {source}
-- Integrand: {integrand}

noncomputable def {name}_antideriv ({var} : ℝ) : ℝ :=
  {antideriv_lean}

noncomputable def {name}_integrand ({var} : ℝ) : ℝ :=
  {integrand_lean}

/-- {description} -/
theorem {name}{hyp_params} :
    HasDerivAt ({name}_antideriv) ({name}_integrand {var}) {var} := by
  unfold {name}_antideriv {name}_integrand
  {proof_hint}
"""

_NO_HYPS_PROOF_HINT = "sorry"
_HYPS_PROOF_HINT = (
    "-- Hypotheses available: {hyp_names}\n  sorry"
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def emit_lean_file(entry: dict[str, Any]) -> str:
    """Return Lean 4 source for a single corpus entry."""
    name        = entry["id"]
    var         = entry.get("variable", "x")
    source      = entry.get("source", "unknown")
    description = entry.get("description", "")
    integrand   = entry.get("integrand", "")
    antideriv   = entry.get("antiderivative", "")

    integrand_lean = fricas_to_lean(integrand)
    antideriv_lean = fricas_to_lean(antideriv)

    hyps = entry.get("required_hypotheses", [])
    hyp_params, hyp_names = _format_hyps(var, hyps)

    if hyps:
        proof_hint = _HYPS_PROOF_HINT.format(hyp_names=", ".join(hyp_names))
    else:
        proof_hint = _NO_HYPS_PROOF_HINT

    return _FILE_TEMPLATE.format(
        name=name,
        var=var,
        source=source,
        description=description,
        integrand=integrand,
        integrand_lean=integrand_lean,
        antideriv_lean=antideriv_lean,
        hyp_params=(" " + hyp_params) if hyp_params else "",
        proof_hint=proof_hint,
    )


def emit_lean_batch(entries: list[dict[str, Any]], module_name: str = "CorpusVerify") -> str:
    """Emit a single .lean file containing all theorems (for CI)."""
    header = (
        "import Mathlib.Analysis.SpecialFunctions.Log.Deriv\n"
        "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv\n\n"
        "open Real\n\n"
        f"-- Auto-generated batch file: {module_name}\n"
        "-- backbone/cas_protocol/lean_emitter.py\n\n"
    )
    blocks: list[str] = []
    for entry in entries:
        blocks.append(_emit_block(entry))
    return header + "\n\n".join(blocks) + "\n"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _format_hyps(var: str, hyps: list[dict]) -> tuple[str, list[str]]:
    """Return (param_string, [name_list]) for theorem signature."""
    params: list[str] = [f"({var} : ℝ)"]
    names: list[str] = []
    for i, h in enumerate(hyps):
        lean_expr = h["lean_expr"]
        hname = f"h{i}"
        params.append(f"({hname} : {lean_expr})")
        names.append(hname)
    return " ".join(params), names


def _emit_block(entry: dict[str, Any]) -> str:
    """Emit function defs + theorem for one entry (no imports, no 'open')."""
    name        = entry["id"]
    var         = entry.get("variable", "x")
    source      = entry.get("source", "unknown")
    description = entry.get("description", "")
    integrand   = entry.get("integrand", "")
    antideriv   = entry.get("antiderivative", "")

    integrand_lean = fricas_to_lean(integrand)
    antideriv_lean = fricas_to_lean(antideriv)

    hyps = entry.get("required_hypotheses", [])
    _, hyp_names = _format_hyps(var, hyps)
    hyp_parts = [f"({var} : ℝ)"]
    for i, h in enumerate(hyps):
        hyp_parts.append(f"(h{i} : {h['lean_expr']})")
    hyp_sig = " ".join(hyp_parts)

    proof_hint = (
        _HYPS_PROOF_HINT.format(hyp_names=", ".join(hyp_names))
        if hyps else _NO_HYPS_PROOF_HINT
    )

    return (
        f"noncomputable def {name}_antideriv ({var} : ℝ) : ℝ :=\n"
        f"  {antideriv_lean}\n\n"
        f"noncomputable def {name}_integrand ({var} : ℝ) : ℝ :=\n"
        f"  {integrand_lean}\n\n"
        f"/-- {source} — {description} -/\n"
        f"theorem risch_{name} {hyp_sig} :\n"
        f"    HasDerivAt ({name}_antideriv) ({name}_integrand {var}) {var} := by\n"
        f"  unfold {name}_antideriv {name}_integrand\n"
        f"  {proof_hint}"
    )
